PROJECT_DIR: './data/projects'

API_ADDRESS: 'http://127.0.0.1:5000'

API_ENDPOINTS:
    LOAD_PROJECTS: '/api/v1/projects'
    CREATE_PROJECT: '/api/v1/project'
    DELETE_PROJECT: '/api/v1/project/delete'
    ADD_DATA: '/api/v1/project/data'
    GET_DATA: '/api/v1/project/data'
    GET_PROJECT_INFO: '/api/v1/project/info'
    UPDATE_PROJECT_INFO: '/api/v1/project/info'
